trigger: ["master"]
pr: ["master"]

resources:
  repositories:
    - repository: templates
      type: github
      name: alecmocatta/azure-pipeline-templates
      endpoint: alecmocatta

jobs:
- template: rust.yml@templates
  parameters:
    endpoint: alecmocatta
    default:
      rust_toolchain: stable nightly
      rust_lint_toolchain: nightly-2020-07-12
      rust_flags: ''
      rust_features: ''
      rust_target_check: 'aarch64-unknown-linux-gnu aarch64-unknown-linux-musl'
      rust_target_build: 'x86_64-unknown-linux-musl i686-unknown-linux-musl'
      rust_target_run: ''
    matrix:
      windows:
        imageName: 'windows-latest'
        rust_target_run: 'x86_64-pc-windows-msvc i686-pc-windows-msvc x86_64-pc-windows-gnu'
      mac0:
        imageName: 'macos-latest'
        rust_target_build: 'x86_64-unknown-linux-musl i686-unknown-linux-musl aarch64-apple-ios'
        rust_target_run: 'x86_64-apple-darwin'
      mac1:
        imageName: 'macos-latest'
        rust_toolchain: nightly
        rust_features: ';nightly'
        rust_target_build: 'x86_64-unknown-linux-musl i686-unknown-linux-musl aarch64-apple-ios'
        rust_target_run: 'x86_64-apple-darwin'
      linux:
        imageName: 'ubuntu-latest'
        rust_target_run: 'x86_64-unknown-linux-gnu i686-unknown-linux-gnu x86_64-unknown-linux-musl i686-unknown-linux-musl'
