[package]
name = "amadeus-postgres"
version = "0.1.7"
license = "Apache-2.0"
authors = ["Alec Mocatta <alec@mocatta.net>"]
categories = ["concurrency", "science", "database", "parser-implementations", "text-processing"]
keywords = ["amadeus", "data", "postgres", "postgresql", "sql"]
description = """
Harmonious distributed data analysis in Rust.
"""
repository = "https://github.com/alecmocatta/amadeus"
homepage = "https://github.com/alecmocatta/amadeus"
documentation = "https://docs.rs/amadeus/0.1.7"
readme = "README.md"
edition = "2018"

[badges]
azure-devops = { project = "alecmocatta/amadeus", pipeline = "tests" }
maintenance = { status = "actively-developed" }

[features]
doc = ["amadeus-core/doc"]

[package.metadata.docs.rs]
features = ["doc"]

[dependencies]
amadeus-core = { version = "=0.1.7", path = "../amadeus-core" }
amadeus-types = { version = "=0.1.7", path = "../amadeus-types" }
chrono = { version = "0.4", default-features = false }
futures = "0.3"
postgres = { version = "0.15", features = ["with-chrono"] }
postgres-binary-copy = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_closure = "0.2"
sum = "0.1"
